### ISSUE TITLE
Need to figure out a value for Park County cattle sales

### ISSUE THREAD

**Issue by mattwilliamson13** [jamiefaselt/jf-bison-thesis#4]
Shouldn't set it to 0, use Inverse distance weighting https://mgimond.github.io/Spatial/interpolation-in-r.html based on county centroids

**Comment by mattwilliamson13** [comment]
In the intermediate `02_cattle_sales_layer`

**Comment by jamiefaselt** [comment]
[5a44e25](https://github.com/jamiefaselt/jf-bison-thesis/commit/5a44e25c6e9049c8780b2d0d9ea196c38db84141)

fixed
